fix mailing service, update to ts
Shard-Labs/betting-app pull request #6
Opened 2020-11-09 13:59 UTC by GitMark0

2020-11-09 14:18 UTC, edisinovcic requested changes

2020-11-09 14:18 UTC, edisinovcic commented on backend/app.ts
> +
Remove space :)

2020-11-09 14:18 UTC, edisinovcic commented on backend/app.ts
> +let data = req.body;
Can this let be converted to const?

2020-11-09 14:18 UTC, edisinovcic commented on backend/app.ts
> +    	html: `I invite you to bet me at ${data.link}!`,
Do you get a link in body? @igor-lid what parameters do you send? One of them could be address of the deployed bet, but not the whole link. As link would look like something like:

`https://ibetyou.me/acceptbet/0xAd52952b325c1dA4d264c5a5e5cefb13CEB7C67B`

where `0xAd52952b325c1dA4d264c5a5e5cefb13CEB7C67B` is the address of the deployed bet contract.

Note acceptbet can be something else. We need to define paths here. @igor-lid you can also propose what would make most sense to you. 

So parameters that frontend would send is not the whole link but just the bet address and other parameters.

2020-11-09 14:18 UTC, edisinovcic commented on backend/tsconfig.json
> +{
Use this tsconfig: https://github.com/ethereum/sourcify/blob/master/tsconfig.json

Just replace include to just include src without other parts.

Also add tslint: https://github.com/ethereum/sourcify/blob/master/tslint.json

And in the package.json add this line: https://github.com/ethereum/sourcify/blob/7b04ede014c5194510a805b646dd5b47b6d33660/package.json#L16

2020-11-09 14:19 UTC, edisinovcic commented
Check why the ci is failing. Did you rebase? @GitMark0

2020-11-10 10:36 UTC, edisinovcic requested changes

2020-11-10 10:36 UTC, edisinovcic commented on backend/package.json
> +    "start": "nodemon --exec ts-node app.ts"
Don't run with nodemon, use build and start scripts from here: https://github.com/ethereum/sourcify/blob/82fd102b4cd28738ddee4f4ff4f97e0bf2b365d1/services/validation/package.json#L19

Problem with nodemon is when app crashes nodemon still runs so we don't know it's not working.

2020-11-10 10:36 UTC, edisinovcic commented on backend/tsconfig.json
> +<<<<<<< HEAD
You have some stuff left over after rebasing.

2020-11-10 12:01 UTC, igor-lid commented on backend/app.ts
> +    	html: `I invite you to bet me at ${data.link}!`,
I will send the address of the deployed bet as @edisinovcic mentioned. 

So the link would be something like `https://ibetyou.me/accept-bet/{betAddress}`.

I need this bet address so I could get information about the bet because the idea is to show this information to the user.

Also, I would like that rename `acceptbet` into `accept-bet` because this is a convention for separating words if I'm not mistaken

2020-11-10 12:57 UTC, edisinovcic commented on backend/app.ts
> +    	html: `I invite you to bet me at ${data.link}!`,
Let the url be: `https://ibetyou.me/accept-bet/{betAddress}`. 

We need data.email ad data.betAddress on the backend, is there anything else needed?

2020-11-10 17:40 UTC, edisinovcic requested changes

2020-11-10 17:40 UTC, edisinovcic commented on backend/app.ts
> +    	from: "no-reply@ibetyou.me",
Just inline these lines also so formating is better.
Lines: 15,16,17,18,21,24. 

Like you did on line 30 it's clearer.

2020-11-15 21:16 UTC, edisinovcic approved these changes

2020-11-15 21:16 UTC, merged